version: "3.8"

services:
  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"
    # depends_on:
    #   - backend

  backend:
    build: ./backend
    command: python app.py
    ports:
      - "6006:6006"
    volumes:
      - ./backend/uploaded_files:/app/uploaded_files
    depends_on:
      - onlyoffice

  onlyoffice:
    image: onlyoffice/documentserver:8.3.3
    container_name: onlyoffice
    ports:
      - "8000:80"  # Exposes container's port 80 as 8000 on your machine
    stdin_open: true
    tty: true
    environment:
      - JWT_ENABLED=false

networks:
  default:
    driver: bridge
